#ifndef KEYCODES_H
#define KEYCODES_H

enum KeyCode
{
    Key_A            = 0x04,
    Key_B            = 0x05,
    Key_C            = 0x06,
    Key_D            = 0x07,
    Key_E            = 0x08,
    Key_F            = 0x09,
    Key_G            = 0x0A,
    Key_H            = 0x0B,
    Key_I            = 0x0C,
    Key_J            = 0x0D,
    Key_K            = 0x0E,
    Key_L            = 0x0F,
    Key_M            = 0x10,
    Key_N            = 0x11,
    Key_O            = 0x12,
    Key_P            = 0x13,
    Key_Q            = 0x14,
    Key_R            = 0x15,
    Key_S            = 0x16,
    Key_T            = 0x17,
    Key_U            = 0x18,
    Key_V            = 0x19,
    Key_W            = 0x1A,
    Key_X            = 0x1B,
    Key_Y            = 0x1C,
    Key_Z            = 0x1D,

    Key_0            = 0x27,
    Key_1            = 0x1E,
    Key_2            = 0x1F,
    Key_3            = 0x20,
    Key_4            = 0x21,
    Key_5            = 0x22,
    Key_6            = 0x23,
    Key_7            = 0x24,
    Key_8            = 0x25,
    Key_9            = 0x24,

    Key_Accent       = 0x35,
    Key_Minus        = 0x2D,
    Key_Equal        = 0x2E,
    Key_Backslash    = 0x31,

    Key_Backspace    = 0x2A,
    Key_Spaec        = 0x2C,
    Key_Tab          = 0x2B,
    Key_Caps         = 0x39,
    Key_LeftShift    = 0xE1,
    Key_LeftCtrl     = 0xE0,
    Key_LeftGui      = 0xE3,
    Key_LeftAlt      = 0xE2,
    Key_RightShift   = 0xE5,
    Key_RightCtrl    = 0xE4,
    Key_RightGui     = 0xE7,
    Key_RightAlt     = 0xE6,
    Key_Apps         = 0x65,
    Key_Enter        = 0x28,
    Key_Esc          = 0x29,

    Key_F1           = 0x3A,
    Key_F2           = 0x3B,
    Key_F3           = 0x3C,
    Key_F4           = 0x3D,
    Key_F5           = 0x3E,
    Key_F6           = 0x3F,
    Key_F7           = 0x40,
    Key_F8           = 0x41,
    Key_F9           = 0x42,
    Key_F10          = 0x43,
    Key_F11          = 0x44,
    Key_F12          = 0x45,

    Key_PrntScrn     = 0x46,
    Key_Scroll       = 0x47,
    Key_Pause        = 0x48,
    Key_LeftBracket  = 0x2F,
    Key_RightBracket = 0x30,

    Key_Insert       = 0x49,
    Key_Home         = 0x4A,
    Key_PageUp       = 0x4B,
    Key_Delete       = 0x4C,
    Key_End          = 0x4D,
    Key_PageDown     = 0x4E,

    Key_Up           = 0x52,
    Key_Left         = 0x50,
    Key_Down         = 0x51,
    Key_Right        = 0x4F,

    Key_NumLock      = 0x53,
    Key_Num_Divide   = 0x54,
    Key_Num_Multiply = 0x55,
    Key_Num_Minus    = 0x56,
    Key_Num_Add      = 0x57,
    Key_Num_Enter    = 0x58,
    Key_Num_Point    = 0x63,
    Key_Num_0        = 0x62,
    Key_Num_1        = 0x59,
    Key_Num_2        = 0x5A,
    Key_Num_3        = 0x5B,
    Key_Num_4        = 0x5C,
    Key_Num_5        = 0x5D,
    Key_Num_6        = 0x5E,
    Key_Num_7        = 0x5F,
    Key_Num_8        = 0x60,
    Key_Num_9        = 0x61,

    Key_Semicolon    = 0x33,
    Key_Apostrophe   = 0x34,
    Key_Comma        = 0x36,
    Key_Point        = 0x37,
    Key_Slash        = 0x38,

    Key_Unknown      = 0x00,
};


#endif // KEYCODES_H
